events {}

http {
    # 1. Redirect semua http ke https
    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri; 
    }

    # 2. Block akses https jika pakai IP langsung
    server {
        listen 443 ssl default_server;
        server_name _;
	
	# Sertifikat SSL Anda (sesuaikan path-nya jika pakai Certbot)
        ssl_certificate /etc/letsencrypt/live/iqbaalcloudporto.site/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/iqbaalcloudporto.site/privkey.pem;
	
	return 403;

   }

    server {
        listen 443 ssl;
        server_name iqbaalcloudporto.site www.iqbaalcloudporto.site;

        ssl_certificate /etc/letsencrypt/live/iqbaalcloudporto.site/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/iqbaalcloudporto.site/privkey.pem;

        # Pengaturan keamanan SSL tambahan (Best Practice)
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://porto-app:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
